In [3]:
import pandas as pd
import numpy as np
import ipywidgets as widgets
from IPython.display import display

In [4]:
# this section will be inactive in final application
df = pd.read_csv('zomato_clean.csv')
df.drop(columns=['Unnamed: 0'], inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12066 entries, 0 to 12065
Data columns (total 12 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   url        12066 non-null  object
 1   address    12066 non-null  object
 2   name       12066 non-null  object
 3   rate       9061 non-null   float64
 4   votes      12066 non-null  int64
 5   phone      12066 non-null  object
 6   location   12066 non-null  object
 7   rest_type  12010 non-null  object
 8   cuisines   12066 non-null  object
 9   cost       12019 non-null  float64
 10  latitude   12066 non-null  float64
 11  longitude  12066 non-null  float64
dtypes: float64(4), int64(1), object(7)
memory usage: 1.1+ MB

In [9]:
slider = widgets.FloatSlider(
    value=4,
    min=0,
    max=5,
    description='Min. rate:',
    readout_format='.1f'
    )

slider

FloatSlider(value=4.0, description='Min. rate:', max=5.0, readout_format='.1f')

In [13]:
slider.value

4.5

In [10]:
def filter_dataframe(dataset, rate):
    df.query(f'rate >= {rate}', inplace=True)
    return df

In [11]:
filter_dataframe(df, slider.value)

,url,address,name,rate,votes,phone,location,rest_type,cuisines,cost,latitude,longitude
7,https://www.zomato.com/bangalore/onesta-banash...,"2469, 3rd Floor, 24th Cross, Opposite BDA Comp...",Onesta,4.6,2556,"08048653961, 08048655715",Banashankari,"Casual Dining, Cafe","['Pizza', 'Cafe', 'Italian']",600.0,12.968006,77.599450
160,https://www.zomato.com/bangalore/the-blue-wago...,"615/1, Ground Floor, Janardhan Mansion, 10th C...",The Blue Wagon - Kitchen,4.6,228,"918105485007, 918095904280",Jayanagar,Cafe,"['Cafe', 'Beverages']",400.0,12.924274,77.586318
177,https://www.zomato.com/bangalore/shakes-theory...,"766/25-01, 47th A Cross, Near Sangam Circle, A...",Shakes Theory,4.5,155,"919886936896, 919620000463",Jayanagar,Beverage Shop,"['Beverages', 'Sandwich']",300.0,12.929526,77.585269
504,https://www.zomato.com/bangalore/taaza-thindi-...,"115, 100 Feet Ring Road, Kathriguppe, Banashan...",Taaza Thindi,4.7,651,08049510845,Banashankari,Quick Bites,['South Indian'],100.0,12.968197,77.590712
598,https://www.zomato.com/bangalore/barbeque-nati...,"67, 15th Cross, 6th B Main, JP Nagar, Bangalore",Barbeque Nation,4.7,3845,918064806060,JP Nagar,Casual Dining,"['North Indian', 'European', 'Mediterranean', ...",1600.0,12.906925,77.580068
...,...,...,...,...,...,...,...,...,...,...,...,...
11709,https://www.zomato.com/bangalore/maziga-whitef...,"3rd Floor, VR Mall, B Narayanapura, Mahadevapu...",Maziga,4.7,292,919606642640,Whitefield,Casual Dining,['Modern Indian'],1500.0,12.971934,77.749971
11925,https://www.zomato.com/bangalore/belgyum-white...,"2nd Floor, Phoenix Market City, Whitefield, Ba...",BelgYum,4.6,1822,"08067266614, 08049626614",Whitefield,Dessert Parlor,['Desserts'],400.0,12.965518,77.747023
11947,https://www.zomato.com/bangalore/feast-sherato...,Sheraton Grand Bengaluru Whitefield Hotel & Co...,Feast - Sheraton Grand Bengaluru Whitefield Ho...,4.5,523,08049652940,Whitefield,Fine Dining,"['Continental', 'Asian', 'South Indian', 'Nort...",2500.0,12.970776,77.751744
11948,https://www.zomato.com/bangalore/the-pallet-wh...,"HVP Crest, ITPL Main Road, Whitefield, Bangalore",The Pallet,4.5,2745,08049652944,Whitefield,"Microbrewery, Pub","['Continental', 'Mediterranean', 'Italian', 'N...",1600.0,12.974272,77.747308
12056,https://www.zomato.com/bangalore/chianti-white...,"1, Ground Floor, Ascendas Park Square Mall, Wh...",Chianti,4.6,848,"918061224716, 918061224717","ITPL Main Road, Whitefield",Casual Dining,['Italian'],1500.0,12.977580,77.728848

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 186 entries, 7 to 12056
Data columns (total 12 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   url        186 non-null    object
 1   address    186 non-null    object
 2   name       186 non-null    object
 3   rate       186 non-null    float64
 4   votes      186 non-null    int64
 5   phone      186 non-null    object
 6   location   186 non-null    object
 7   rest_type  186 non-null    object
 8   cuisines   186 non-null    object
 9   cost       186 non-null    float64
 10  latitude   186 non-null    float64
 11  longitude  186 non-null    float64
dtypes: float64(4), int64(1), object(7)
memory usage: 18.9+ KB